# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa00db9d4e2274ddddd0745b78d8ad00d850cba19566250408afedc066ca60f458fe2cf1b524c395c5282985b1282ea746d98bccf8817fa8a786ea091cb793a0

test:
  secret_key_base: b7142bac8858e31ab862dbfdd70b63fb0d6f5b4d3bc319327470962a0819de631f351efa8f15db12f2879eecf2249e6f67eca1b6aa0350879a8ee2a129f6d68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
